# Final Assignment Week 3 (Part 1 and 2)

## Part 1

In [1]:
import pandas as pd
import numpy as np
print ("Libraries imported")

Libraries imported

In [2]:
url = "https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M"
pd.read_html(url, attrs={"class": "wikitable"})

[    Postal code           Borough  \
 0           M1A      Not assigned
 1           M2A      Not assigned
 2           M3A        North York
 3           M4A        North York
 4           M5A  Downtown Toronto
 5           M6A        North York
 6           M7A  Downtown Toronto
 7           M8A      Not assigned
 8           M9A         Etobicoke
 9           M1B       Scarborough
 10          M2B      Not assigned
 11          M3B        North York
 12          M4B         East York
 13          M5B  Downtown Toronto
 14          M6B        North York
 15          M7B      Not assigned
 16          M8B      Not assigned
 17          M9B         Etobicoke
 18          M1C       Scarborough
 19          M2C      Not assigned
 20          M3C        North York
 21          M4C         East York
 22          M5C  Downtown Toronto
 23          M6C              York
 24          M7C      Not assigned
 25          M8C      Not assigned
 26          M9C         Etobicoke
 27          M1E       Scarborough
 28          M2E      Not assigned
 29          M3E      Not assigned
 ..          ...               ...
 150         M7W      Not assigned
 151         M8W         Etobicoke
 152         M9W         Etobicoke
 153         M1X       Scarborough
 154         M2X      Not assigned
 155         M3X      Not assigned
 156         M4X  Downtown Toronto
 157         M5X  Downtown Toronto
 158         M6X      Not assigned
 159         M7X      Not assigned
 160         M8X         Etobicoke
 161         M9X      Not assigned
 162         M1Y      Not assigned
 163         M2Y      Not assigned
 164         M3Y      Not assigned
 165         M4Y  Downtown Toronto
 166         M5Y      Not assigned
 167         M6Y      Not assigned
 168         M7Y      East Toronto
 169         M8Y         Etobicoke
 170         M9Y      Not assigned
 171         M1Z      Not assigned
 172         M2Z      Not assigned
 173         M3Z      Not assigned
 174         M4Z      Not assigned
 175         M5Z      Not assigned
 176         M6Z      Not assigned
 177         M7Z      Not assigned
 178         M8Z         Etobicoke
 179         M9Z      Not assigned

                                           Neighborhood
 0                                                  NaN
 1                                                  NaN
 2                                            Parkwoods
 3                                     Victoria Village
 4                           Regent Park / Harbourfront
 5                    Lawrence Manor / Lawrence Heights
 6         Queen's Park / Ontario Provincial Government
 7                                                  NaN
 8                                     Islington Avenue
 9                                      Malvern / Rouge
 10                                                 NaN
 11                                           Don Mills
 12                    Parkview Hill / Woodbine Gardens
 13                            Garden District, Ryerson
 14                                           Glencairn
 15                                                 NaN
 16                                                 NaN
 17   West Deane Park / Princess Gardens / Martin Gr...
 18            Rouge Hill / Port Union / Highland Creek
 19                                                 NaN
 20                                           Don Mills
 21                                    Woodbine Heights
 22                                      St. James Town
 23                                  Humewood-Cedarvale
 24                                                 NaN
 25                                                 NaN
 26   Eringate / Bloordale Gardens / Old Burnhamthor...
 27                 Guildwood / Morningside / West Hill
 28                                                 NaN
 29                                                 NaN
 ..                                                 ...
 150                                                NaN
 151                            Alderwood / Long Branch
 152                                          Northwest
 153                                        Upper Rouge
 154                                                NaN
 155                                                NaN
 156                       St. James Town / Cabbagetown
 157            First Canadian Place / Underground city
 158                                                NaN
 159                                                NaN
 160    The Kingsway / Montgomery Road / Old Mill North
 161                                                NaN
 162                                                NaN
 163                                                NaN
 164                                                NaN
 165                               Church and Wellesley
 166                                                NaN
 167                                                NaN
 168              Business reply mail Processing CentrE
 169  Old Mill South / King's Mill Park / Sunnylea /...
 170                                                NaN
 171                                                NaN
 172                                                NaN
 173                                                NaN
 174                                                NaN
 175                                                NaN
 176                                                NaN
 177                                                NaN
 178  Mimico NW / The Queensway West / South of Bloo...
 179                                                NaN

 [180 rows x 3 columns]]

In [3]:
df = pd.read_html('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M')[0]
df.head()

  Postal code           Borough                Neighborhood
0         M1A      Not assigned                         NaN
1         M2A      Not assigned                         NaN
2         M3A        North York                   Parkwoods
3         M4A        North York            Victoria Village
4         M5A  Downtown Toronto  Regent Park / Harbourfront

In [4]:
df.replace("Not assigned", np.nan, inplace = True)
df.head(5)

  Postal code           Borough                Neighborhood
0         M1A               NaN                         NaN
1         M2A               NaN                         NaN
2         M3A        North York                   Parkwoods
3         M4A        North York            Victoria Village
4         M5A  Downtown Toronto  Regent Park / Harbourfront

In [5]:
df.dropna(subset=["Borough"], axis=0, inplace=True)
df.reset_index(drop=True, inplace=True)
df.head()

  Postal code           Borough                                  Neighborhood
0         M3A        North York                                     Parkwoods
1         M4A        North York                              Victoria Village
2         M5A  Downtown Toronto                    Regent Park / Harbourfront
3         M6A        North York             Lawrence Manor / Lawrence Heights
4         M7A  Downtown Toronto  Queen's Park / Ontario Provincial Government

In [6]:
df["Neighborhood"] = df["Neighborhood"].str.replace ("/", ",")
df.head()

  Postal code           Borough                                  Neighborhood
0         M3A        North York                                     Parkwoods
1         M4A        North York                              Victoria Village
2         M5A  Downtown Toronto                    Regent Park , Harbourfront
3         M6A        North York             Lawrence Manor , Lawrence Heights
4         M7A  Downtown Toronto  Queen's Park , Ontario Provincial Government

In [7]:
df.shape[0]

103

## Part 2

In [8]:
# Load coordinate data from CSV
geo_df = pd.read_csv('http://cocl.us/Geospatial_data')
# This assumes that the postal code column in your main dataframe is labelled 'PostalCode', this renames the column from the geo csv so the merge can happen automatically and cleanly
geo_df = geo_df.rename({'Postal Code':'PostalCode'}, axis=1)
geo_df.head()

  PostalCode   Latitude  Longitude
0        M1B  43.806686 -79.194353
1        M1C  43.784535 -79.160497
2        M1E  43.763573 -79.188711
3        M1G  43.770992 -79.216917
4        M1H  43.773136 -79.239476

In [9]:
df = pd.merge(df, geo_df, left_on='Postal code', right_on='PostalCode')
df.head()

,Postal code,Borough,Neighborhood,PostalCode,Latitude,Longitude
0,M3A,North York,Parkwoods,M3A,43.753259,-79.329656
1,M4A,North York,Victoria Village,M4A,43.725882,-79.315572
2,M5A,Downtown Toronto,"Regent Park , Harbourfront",M5A,43.654260,-79.360636
3,M6A,North York,"Lawrence Manor , Lawrence Heights",M6A,43.718518,-79.464763
4,M7A,Downtown Toronto,"Queen's Park , Ontario Provincial Government",M7A,43.662301,-79.389494

In [10]:
df = df.drop(['PostalCode'], axis=1)
df.head()

,Postal code,Borough,Neighborhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,"Regent Park , Harbourfront",43.654260,-79.360636
3,M6A,North York,"Lawrence Manor , Lawrence Heights",43.718518,-79.464763
4,M7A,Downtown Toronto,"Queen's Park , Ontario Provincial Government",43.662301,-79.389494

In [12]:
CLIENT_ID = 'XREXEZYTVIN3WECWJIF3HRMEZNIDG1V2LIPMOSCWFRZ0VMH2' # your Foursquare ID
CLIENT_SECRET = '31EF1T1GJ34Y4FPQN0Z3UYO5EMYESUWYNX23MWDQUB44QEGP' # your Foursquare Secret
VERSION = '20180605' # Foursquare API version

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: XREXEZYTVIN3WECWJIF3HRMEZNIDG1V2LIPMOSCWFRZ0VMH2
CLIENT_SECRET:31EF1T1GJ34Y4FPQN0Z3UYO5EMYESUWYNX23MWDQUB44QEGP